module problem002

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
fibonacci = Int64[1, 2]
while fibonacci[end] < 4000000
    push!(fibonacci, fibonacci[end] + fibonacci[end-1])
end
n = sum(filter((x) -> iseven(x), fibonacci))
println(n)

end