""" 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By 
starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

def fibonacciSum(maxNum):
    termOne = 1
    termTwo = 2
    sumEven = 2
    termCurrent = termOne + termTwo

    while termCurrent < maxNum:
        if termCurrent % 2 == 0:
            sumEven += termCurrent
        termOne = termTwo
        termTwo = termCurrent
        termCurrent = termOne + termTwo
        
    return sumEven

def main():
    maxNum = 4000000
    ans = fibonacciSum(maxNum)
    print(ans)

if __name__ == "__main__":
    main()